development:
  sessions:
    default:
      database: paas
      hosts:
          - 127.0.0.1:27017

test:
  sessions:
    default:
      database: paas_test
      hosts:
        - 127.0.0.1:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>